### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by pavanyogi** [hypercore-protocol/p2p-multiwriter-with-autobase#11]
We are getting error during execution of these files.

The error is:

`pavany@u-16:~/.../05-Hypernews$ hrepl hypernews.js
Autobase setup. Pass this to run this same setup in another instance:

file:///home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/05-Hypernews/hypernews.js:95
      this.autobase.defaultIndexes.map(i => '-i ' + i.key.toString('hex')).join(' ')
                                   ^

TypeError: Cannot read property 'map' of undefined
    at Hypernews.info (file:///home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/05-Hypernews/hypernews.js:95:36)
    at Hypernews.start (file:///home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/05-Hypernews/hypernews.js:60:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/05-Hypernews/hypernews.js:113:1
pavany@u-16:~/.../05-Hypernews$`

Are we missing something here? The codebase is hosted on https://github.com/Qbix/HypercorePlayground/ .

**Comment by mafintosh** [comment]
@andrewosh o/ i think your recent api upgrade broke that exercise?

**Comment by andrewosh** [comment]
Yep, that should be `this.autobase.defaultOutputs` -- the problem has been updated now. Sorry again @pavanyogi, you caught us in between a big Autobase update, and the update to this workshop.
