### ISSUE TITLE
Problem 3: Core not flushing? 

### ISSUE THREAD

**Issue by SonnyAD** [hypercore-protocol/p2p-multiwriter-with-autobase#8]
Hi, 

I have a question on the second part of the problem. 

If I run the seed with 10K blocks, connect a peer, the peer says Core length is 10K.
Then, if I change seed.js to generate 2K blocks, connect a peer, the peer says Core length is 2K. 

What is happening here? I guess the core does not expire right away? But also why if I rerun the seed it does not append to the current core?

**Comment by SonnyAD** [comment]
Ah wait actually the while loop won't append because it's looking at the core length. 

So I tried to replace the while loop by a for loop something like this: 
```
for (let i = 0; i < 2222; i++) {
  await core.append(Buffer.from('the next block of data. #' + core.length))
}
```
But my peer is still displaying 10K and not 12222.

**Comment by mafintosh** [comment]
The replicating peer?

**Comment by mafintosh** [comment]
Can you show the full gist you are using to append?

**Comment by SonnyAD** [comment]
Sure, here is my seed.js
```
import Corestore from 'corestore'
import Hyperswarm from 'hyperswarm'

const store = new Corestore('./seed-store')
const swarm = new Hyperswarm()

// Setup corestore replication
swarm.on('connection', (connection) => store.replicate(connection))

// Load a core by name
const core = store.get({ name: 'seeding-core4' })

// Make sure the length is loaded
await core.ready()

// Join the Hypercore discoveryKey (a hash of it's public key)
swarm.join(core.discoveryKey)

// Insert 10000 blocks
for (let i = 0; i < 2222; i++) {
  await core.append(Buffer.from('the next block of data. #' + core.length))
  console.log('appended block #' + core.length)
}

console.log('Core public key is:', core.key.toString('hex'))
```

and my peer.js
```
import Corestore from 'corestore'
import Hyperswarm from 'hyperswarm'

const store = new Corestore('./peer-store')
const swarm = new Hyperswarm()

// Setup corestore replication
swarm.on('connection', (connection) => store.replicate(connection))

// Load a core by public key
const core = store.get(Buffer.from('b8c37cbce29be7e26fc1a30f84d39e0e8a288fde80f435c33ed44cae83193742', 'hex'))

await core.ready()

// Join the Hypercore discoveryKey (a hash of it's public key)
swarm.join(core.discoveryKey)

// Make sure we have all the connections
await swarm.flush()

// Make sure we have the latest length
await core.update()

// Print the length (should print 10000)
console.log('Core length is:', core.length)
```

**Comment by SonnyAD** [comment]
Actually my console log from the seed.js is correct, it does increase the core length with multiple runs. 
But the peer console log Core length is still showing a length of 10K.

**Comment by mafintosh** [comment]
You 100% sure you are replicating the right core?

**Comment by SonnyAD** [comment]
At each run of seed.js I do have the public key b8c37cbce29be7e26fc1a30f84d39e0e8a288fde80f435c33ed44cae83193742 displayed in the console, that one I put in peer.js. 

Quick question from peer.js should I be able to retrieve the core using its name: 
```
const core = store.get({ name: 'seeding-core4' }
```
?
I can't right? This is how the trustless is done, because only the one who initiated the core has the private key.

**Comment by mafintosh** [comment]
Yea, peer.js needs the public key for trust.

**Comment by mafintosh** [comment]
Hmm okay, it should auto get the latest length, but good that, that worked at least :)
